Tell logrotate that it's OK that /var/log/requests is publicly writable
The errors were:

    error: skipping "/var/log/requests/0:0:0:0:0:0:0:1" because parent
    directory has insecure permissions (It's world writable or writable
    by group which is not "root") Set "su" directive in config file to
    tell logrotate which user/group should be used for rotation.

    error: skipping "/var/log/requests/README" because parent directory
    has insecure permissions (It's world writable or writable by group
    which is not "root") Set "su" directive in config file to tell
    logrotate which user/group should be used for rotation.

So we need to explicitly tell it that we want it to handle the logs as
root.

Incidentally this lets us remove the "FIXME" from the integration test.